version: "3.8"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_HOST: "spartasix.cjkaciro9eyb.ap-northeast-2.rds.amazonaws.com" # If you're using Docker Desktop on Windows or macOS
      # DATABASE_HOST: '<your_local_machine_IP>' # If you're using Docker on Linux
      DATABASE_PORT: 3306
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: jung1234
      DATABASE_NAME: project_7
      DATABASE_SYNCHRONIZE: true
      PORT: 3000
      JWT_SECRET: "team6_project_jwt_secret_key"
      REDIS_HOST: "redis"
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: "redis:latest"
    command: redis-server --bind '0.0.0.0'
    ports:
      - "6379:6379"
